### ISSUE TITLE
Optimized calcBitNum

### ISSUE THREAD

**Issue by metopa** [maratig/go-trie#1]
I believe (I didn't measured it though), that `calcBitNum` can be sped up by replacing a chain of `if` operators with a precomputed array of 256 elements.
The array would contain char index for valid chars and -1 for others.
Something like 
```go
table := [...]int64{-1, -1, ..., 0,  1,  2, ..., 9, -1, ..., 10, 11, 12, ...}
                   //           '0' '1' '2'     '9'          'a' 'b' 'c'

func calcBitNum(char rune) (uint64, bool) {
    index := table[rune]
    if index == -1 {
        return 0, false
    }
    return uint64(index), true
}
```

**Comment by maratig** [comment]
Yes, it definitely should increase performance. I will try and put results here some time later.
Also I believe there are more places to improve. Thank you

**Comment by maratig** [comment]
I changed the bit number calculation way and now it uses an array as discussed earlier. Now calcBitNum function works 2-3 times faster. The total speed for tree increased to 1-2%.
